#!/usr/bin/perl

use strict;

unless (@ARGV == 6){
print "\nUsage: 	perl search_exonerate_ryo.pl\n
			input_file\n
			Percent of alignment length from total read length, i.e. 80 (80% of read length has to align)\n
			\%_id (no decimal points i.e. 92 NOT 92.31)\n
			overlap_on OR overlap_off OR duplication (to detect duplicate or embedded clones)\n
			alignment_start_offset (i.e. start at 0 or 10 or 50 etc..)\n
			minimum extension length of query, target or both(e.g. 100_query, 1000_target, 5000_both etc.\n\n";
	exit;
}

open (FH,"$ARGV[0]") || die "Cannot open input file\n";

my $overlap_length	= $ARGV[1];
my $percent_id		= $ARGV[2];
#print"*****$percent_id*****\n";
my $overlap_mode 	= $ARGV[3];
my $start_of_alignment 	= $ARGV[4];
my $extension_length 	= $ARGV[5];
$extension_length	=~ /^(.+)\_\w+/;
my $extension_length2	= $1;
$extension_length       =~ /^.+\_(\w+)/;
my $extension_type	= $1;
my $second_length;
#my $percent_id;
my $overlap;
my $bac1;
my $bac2;
my $first_start;
my $first_end;
my $first_strand;
my $first_length;
my $first_bac_length;
my $second_start;
my $second_end;
my $second_strand;
my $second_bac_length;
my $match_id;
my $extension_diff_query;
my $extension_diff_target;

while (<FH>){

	if(/ryo\t(.+)\:(\d+)\-(\d+)\:([+-])\:(\d+)\-(\d+)\t(.+)\:(\d+)\-(\d+)\:([+-])\:(\d+)\-(\d+)\t(\d+)\..+/){

	$bac1             	= $1;
	$first_start      	= $2;
	$first_end        	= $3;
	$first_strand     	= $4;
	$first_length     	= $5;
	$first_bac_length 	= $6;
	$bac2             	= $7;
	$second_start           = $8;
	$second_end             = $9;
	$second_strand          = $10;
	$second_length          = $11;
	$second_bac_length      = $12;
	$match_id         	= $13;
	$extension_diff_query	= $first_bac_length - $first_length;
	$extension_diff_target	= $second_bac_length - $second_length;
	$overlap		= ($overlap_length/100)*$first_bac_length;
#print "++++$overlap\t$overlap_length+++++\n";


			############### Overlap On extension query ################

		if (	$overlap_mode		eq	'overlap_on'		and 
			$match_id		>=	$percent_id		and 
			$first_length		ne	$first_bac_length	and 
			$second_length		ne	$second_bac_length	and 
			$first_length		>=	$overlap		and
			$extension_diff_query	>=	$extension_length2	and
			$extension_type		eq	'query'			){

			unless ($bac1 eq $bac2){

				if ((	$first_start	<=	(0+$start_of_alignment)			or
					$first_end	>=	($first_bac_length-$start_of_alignment)	or
					$first_start	>=	($first_bac_length-$start_of_alignment)	or
					$first_end	<=	(0+$start_of_alignment)			) 
								and
				    (	$second_start	<=	(0+$start_of_alignment)				or
					$second_end	>=	($second_bac_length-$start_of_alignment)	or
					$second_start	>=	($second_bac_length-$start_of_alignment)	or
					$second_end	<=	(0+$start_of_alignment))			){
					print "$_";
				}
			}
		}

			############### Overlap On extension target ################

                if (    $overlap_mode            eq      'overlap_on'            and
                        $match_id                >=      $percent_id             and
                        $first_length            ne      $first_bac_length       and
                        $second_length		 ne      $second_bac_length      and
                        $first_length          	 >=      $overlap                and
                        $extension_diff_target   >=      $extension_length2      and
                        $extension_type          eq      'target'                 ){

                        unless ($bac1 eq $bac2){

                                if ((   $first_start    <=      (0+$start_of_alignment)                 or
                                        $first_end      >=      ($first_bac_length-$start_of_alignment) or
                                        $first_start    >=      ($first_bac_length-$start_of_alignment) or
                                        $first_end      <=      (0+$start_of_alignment)                 )
                                                                and
                                    (   $second_start   <=      (0+$start_of_alignment)                         or
                                        $second_end     >=      ($second_bac_length-$start_of_alignment)        or
                                        $second_start   >=      ($second_bac_length-$start_of_alignment)        or
                                        $second_end     <=      (0+$start_of_alignment))                        ){
                                        print "$_";
                                }
                        }
                }


			############### Overlap On extension both ################

                if (    $overlap_mode            eq      'overlap_on'            and
                        $match_id                >=      $percent_id             and
                        $first_length            ne      $first_bac_length       and
                        $second_length           ne      $second_bac_length      and
                        $first_length            >=      $overlap                and
                        $extension_diff_query    >=      $extension_length2      and
			$extension_diff_target   >=      $extension_length2      and
                        $extension_type          eq      'both'                 ){

                        unless ($bac1 eq $bac2){

                                if ((   $first_start    <=      (0+$start_of_alignment)                 or
                                        $first_end      >=      ($first_bac_length-$start_of_alignment) or
                                        $first_start    >=      ($first_bac_length-$start_of_alignment) or
                                        $first_end      <=      (0+$start_of_alignment)                 )
                                                                and
                                    (   $second_start   <=      (0+$start_of_alignment)                         or
                                        $second_end     >=      ($second_bac_length-$start_of_alignment)        or
                                        $second_start   >=      ($second_bac_length-$start_of_alignment)        or
                                        $second_end     <=      (0+$start_of_alignment))                        ){
                                        print "$_";
                                }
                        }
                }


			############### Overlap Off ################
		if (	$overlap_mode	eq	'overlap_off'	and
			$match_id	>=	$percent_id	and
			$first_length   >=      $overlap	){

			unless (	$bac1	eq	$bac2	){

			print "$_";
			
			}
		}
		

			############### Duplication ################
		if (	$overlap_mode	eq	'duplication'	and	$bac1	ne	$bac2	){
		
			if (	
				$first_length	>=	$overlap					and
				$match_id       >=      $percent_id					and
				($first_length	>=	($first_bac_length - $start_of_alignment)	or
				$second_length	eq	($second_bac_length - $start_of_alignment))	){
			#print "+++++++$match_id\t$percent_id\t$overlap\t$first_length++++++++\n$_";
			print"$_";
			}
		}
	}
}

